### ISSUE TITLE
Installing with Petsc and GCC 5

### ISSUE THREAD

**Issue by wrighematthey** [OpenFCST/OpenFCST_v0.2#1]
The GCC compiler has now moved on to version 5 which seems to cause some issues with installing OpenFCST v0.2.  The standard installation works fine but there are some small differences in the response currents in the test curves (3rd / 4th sig fig).  When I try to compile with Petsc to allow parallel solving, the installation fails.  I've installed Petsc using YAST but I can't figure out how to use the installation directory flags to point to the correct place - which directory is it looking for and what is the format of the path (eg does it need to be in quotes)?

**Comment by wrighematthey** [comment]
Having looked a bit more closely, it appears that the issue came from the PETSc python script not liking the system python having been switched to python 3 by installing anaconda.  Running from a python 2 environment succeeded but will have to see how the tests run.  I may also need to check which GCC was used as the rest seemed fine...

**Comment by wrighematthey** [comment]
After trying to run the simplest cathode example, the install does not appear to have worked and is not converging.  I've attached the logfile just in case it helps anyone.
[logfile.txt](https://github.com/OpenFCST/OpenFCST_v0.2/files/455085/logfile.txt)

**Comment by wrighematthey** [comment]
I have now checked and the PETSc install was failing due to the system python having changed to python 3 which led to an error with the PETSc configuration script.  Having run this again using python 2, the install proceeds but when attempting to run the cathode analysis example, this fails to converge.

**Comment by wrighematthey** [comment]
After further checking, the python version also accounted for the reported issues in the test suite.  I'm no longer sure if I have been compiling with GCC4.8 or GCC5 as both are installed. - After checking the log files it appears that the 4.8.5 compiler is being used.

**Comment by OpenFCST** [comment]
Ed, we are aware of this issue. Release 0.3 should fix this problem
