### ISSUE TITLE
installation problem with boost

### ISSUE THREAD

**Issue by christineleroy** [OpenFCST/OpenFCST_v0.2#2]
Hello,

While installing OpenFCST_v02, I encounter this error(*).
Could you help me?
Thanks,
Christine

OpenFCST/Build/contrib/deal.II/src/source/base/parameter_handler.cc: In static member function \u2018static bool dealii::ParameterHandler::is_parameter_node(
const ptree&)\u2019:
OpenFCST/Build/contrib/deal.II/src/source/base/parameter_handler.cc:1278:47: error: cannot convert \u2018boost::optionalstd::basic_string<char >\u2019 to \u2018bool\u2019
 in return
   return (p.get_optionalstd::string("value"));
                                               ^
OpenFCST/Build/contrib/deal.II/src/source/base/parameter_handler.cc:1279:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[5]: **\* [source/base/CMakeFiles/obj_base.release.dir/parameter_handler.cc.o] Error 1
make[4]: **\* [source/base/CMakeFiles/obj_base.release.dir/all] Error 2
make[3]: **\* [all] Error 2

**Comment by OpenFCST** [comment]
Which version of CMake and GCC are you using?
What OS and version are you using?

**Comment by christineleroy** [comment]
Hi,

I ‘ve already resolved the problem installing a more recent boost version.
Also what I needed to do:

·         Installation dealii 8.2.0

·         Modification file : OpenFCST/src/fcst/include/utils/logging.h et logging.cc :

o   Comment line “if (Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0)”

o   Add   « #include <iostream> »

Best regards,
Christin Leroy

De : OpenFCST project [mailto:notifications@github.com]
Envoyé : lundi 26 septembre 2016 01:39
À : OpenFCST/OpenFCST_v0.2 OpenFCST_v0.2@noreply.github.com
Cc : LEROY Christine 208562 Christine.LEROY2@cea.fr; Author author@noreply.github.com
Objet : Re: [OpenFCST/OpenFCST_v0.2] installation problem with boost (#2)

Which version of CMake and GCC are you using?
What OS and version are you using?
