### ISSUE TITLE
Issue with writeVTK

### ISSUE THREAD

**Issue by wrighematthey** [OpenFCST/OpenFCST_v0.2#3]
I am having an issue with the writeVTK python script.  I have tried to debug as best as I can and it appears that the issue is related to a version incompatibility with tvtk.  I am using version 4.4.0 which does not have a set_input_data attribute for UnstructuredGridWriter objects and so it is failing at that point.  Do you know which version of tvtk it was written for and what the equivalent command is for v 4.4.0?

**Comment by OpenFCST** [comment]
This issue has been resolved in v0.3. OpenFCST now contains instructions on how to create a CONDA environment that contains all the necessary packages to run the writeVTK. 
Please download the newest version and post a new issues if you have any problems.
